# language: objective-c
# osx_image: xcode7.3
# env:
#   global:
#   - LC_CTYPE=en_US.UTF-8
#   - LANG=en_US.UTF-8
# xcode_workspace: graph-API-search.xcworkspace
# xcode_scheme: graph-API-search
# xcode_sdk: iphonesimulator9.3
#script: xcodebuild GCC_GENERATE_TEST_COVERAGE_FILES=YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest' -workspace dtac-iservice.xcworkspace -scheme "dtac-iservice" clean build test
#language: objective-c
# script:
  # - xctool -workspace dtac-iservice.xcworkspace -scheme dtac-iservice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  # - xctool test -workspace dtac-iservice.xcworkspace -scheme dtac-iservice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  # - xcodebuild -workspace graph-API-search.xcworkspace -scheme graph-API-search -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest' build test
language: objective-c
script:
  - xcodebuild -project graph-API-search.xcodeproj -scheme graph-API-search -sdk iphonesimulator
